export const nonograms = [
  {
    id: 1,
    name: 'Baby carriage',
    width: 5,
    height: 5,
    difficulty: 'easy',
    scheme: [
      [false, true, true, false, false],
      [true, true, false, false, true],
      [true, true, true, true, false],
      [false, true, true, false, false],
      [true, false, false, true, false],
    ],
  },
  {
    id: 2,
    name: 'Rabbit',
    width: 5,
    height: 5,
    difficulty: 'easy',
    scheme: [
      [false, true, true, false, false],
      [false, false, false, true, true],
      [false, true, true, true, true],
      [true, true, true, true, false],
      [false, true, true, true, true],
    ],
  },
  {
    id: 3,
    name: 'Camel',
    width: 5,
    height: 5,
    difficulty: 'easy',
    scheme: [
      [false, false, false, true, true],
      [true, true, false, true, false],
      [true, true, true, true, false],
      [true, false, true, false, false],
      [true, false, true, false, false],
    ],
  },
  {
    id: 4,
    name: 'Clock',
    width: 5,
    height: 5,
    difficulty: 'easy',
    scheme: [
      [false, true, true, true, false],
      [true, false, true, false, true],
      [true, false, true, true, true],
      [true, false, false, false, true],
      [false, true, true, true, false],
    ],
  },
  {
    id: 5,
    name: 'Heart',
    width: 5,
    height: 5,
    difficulty: 'easy',
    scheme: [
      [false, true, false, true, false],
      [true, true, true, true, true],
      [true, true, true, true, true],
      [false, true, true, true, false],
      [false, false, true, false, false],
    ],
  },
  {
    id: 6,
    name: 'Deer',
    width: 10,
    height: 10,
    difficulty: 'medium',
    scheme: [
      [false, false, false, true, false, true, false, false, true, false],
      [false, false, false, false, true, true, false, true, false, false],
      [false, false, false, false, false, true, true, true, true, false],
      [false, true, false, false, false, false, true, false, true, true],
      [true, true, false, false, false, false, true, true, false, false],
      [false, false, true, true, true, true, false, false, true, false],
      [false, true, false, false, false, false, false, true, true, false],
      [false, true, true, false, true, true, true, false, false, true],
      [true, true, false, true, false, false, true, false, true, true],
      [true, false, false, true, false, false, true, false, false, false],
    ],
  },
  {
    id: 7,
    name: 'Moon',
    width: 10,
    height: 10,
    difficulty: 'easy',
    scheme: [
      [false, false, false, true, true, true, true, false, false, false],
      [false, true, true, true, false, false, false, false, true, false],
      [false, true, true, false, false, false, false, true, true, true],
      [true, true, false, false, false, false, false, false, true, false],
      [true, true, false, false, false, false, false, false, false, false],
      [true, true, false, false, false, false, false, false, false, false],
      [true, true, true, false, false, false, false, false, false, true],
      [false, true, true, true, false, false, false, false, true, false],
      [false, true, true, true, true, true, true, true, true, false],
      [false, false, false, true, true, true, true, false, false, false],
    ],
  },
  {
    id: 8,
    name: 'Bunny',
    width: 10,
    height: 10,
    difficulty: 'easy',
    scheme: [
      [true, true, true, true, false, false, false, false, true, true],
      [true, true, true, false, false, false, false, true, true, true],
      [true, false, false, false, true, true, true, true, true, true],
      [false, true, false, false, true, true, true, true, true, true],
      [false, false, false, false, false, false, false, true, true, true],
      [true, true, false, false, false, false, false, false, true, true],
      [true, true, false, false, false, false, false, false, false, true],
      [true, true, false, true, false, false, false, false, false, false],
      [true, true, true, true, true, false, false, false, false, true],
      [true, true, true, false, false, false, false, false, true, true],
    ],
  },
  {
    id: 9,
    name: 'Duck',
    width: 10,
    height: 10,
    difficulty: 'medium',
    scheme: [
      [false, false, false, true, true, true, false, false, false, false],
      [false, false, true, false, false, false, true, false, false, false],
      [false, false, true, false, true, false, true, false, false, false],
      [false, true, true, true, false, false, true, false, false, false],
      [true, true, true, true, true, false, true, false, false, false],
      [false, false, false, true, false, true, false, false, false, true],
      [false, false, true, false, false, false, true, true, true, true],
      [false, true, false, false, true, false, false, false, false, true],
      [false, true, false, false, true, true, false, false, true, true],
      [false, true, true, false, false, true, true, true, false, true],
    ],
  },
  {
    id: 10,
    name: 'Parrot',
    width: 10,
    height: 10,
    difficulty: 'hard',
    scheme: [
      [false, false, false, false, false, false, false, false, true, false],
      [false, false, false, false, false, false, false, true, true, false],
      [false, false, false, false, false, true, true, true, false, true],
      [false, false, true, true, true, true, true, false, true, true],
      [false, true, true, false, false, false, true, true, true, false],
      [true, true, false, true, false, false, true, false, false, false],
      [true, true, true, false, false, false, true, false, false, false],
      [true, false, false, true, false, false, true, false, false, false],
      [false, false, false, true, false, false, true, true, false, false],
      [false, false, false, true, false, false, false, true, true, false],
    ],
  },
  {
    id: 11,
    name: 'Cat',
    width: 15,
    height: 15,
    difficulty: 'medium',
    scheme: [
      [
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        true,
        false,
        false,
        false,
        false,
        true,
        true,
        true,
        true,
        false,
        false,
        false,
        true,
        true,
        false,
      ],
      [
        true,
        true,
        false,
        false,
        true,
        true,
        true,
        true,
        true,
        false,
        false,
        true,
        false,
        false,
        false,
      ],
      [
        false,
        true,
        true,
        false,
        true,
        true,
        true,
        true,
        true,
        false,
        false,
        true,
        true,
        false,
        false,
      ],
      [
        true,
        false,
        true,
        true,
        false,
        true,
        true,
        true,
        true,
        false,
        false,
        false,
        true,
        true,
        false,
      ],
      [
        true,
        false,
        true,
        true,
        true,
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
      ],
      [
        true,
        true,
        false,
        true,
        true,
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        true,
        true,
      ],
      [
        false,
        true,
        true,
        false,
        true,
        true,
        true,
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
      ],
      [false, false, true, true, true, true, true, true, true, true, true, true, true, false, true],
      [true, false, false, true, true, true, true, true, true, true, true, true, true, true, false],
      [true, true, false, false, false, true, true, true, true, true, true, true, true, true, true],
      [true, true, true, false, false, false, true, true, true, true, true, true, true, true, true],
      [
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
      ],
      [
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        false,
      ],
      [
        true,
        true,
        true,
        false,
        false,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        false,
        false,
      ],
    ],
  },
  {
    id: 12,
    name: 'Swan',
    width: 15,
    height: 15,
    difficulty: 'hard',
    scheme: [
      [
        false,
        false,
        false,
        true,
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        true,
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        true,
        true,
        true,
        true,
        false,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        true,
        true,
        false,
        true,
        true,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        true,
        true,
        false,
        false,
        false,
        true,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        true,
        false,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        true,
        false,
        true,
        true,
        false,
        false,
        true,
        true,
        true,
        true,
        true,
        false,
      ],
      [
        false,
        false,
        true,
        false,
        true,
        true,
        false,
        true,
        true,
        true,
        false,
        false,
        false,
        true,
        true,
      ],
      [
        false,
        true,
        true,
        false,
        true,
        false,
        true,
        true,
        false,
        false,
        false,
        true,
        true,
        true,
        false,
      ],
      [
        true,
        true,
        false,
        false,
        true,
        true,
        true,
        false,
        false,
        true,
        true,
        false,
        true,
        false,
        false,
      ],
      [
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        true,
        true,
        false,
        false,
        true,
        true,
        true,
        false,
      ],
      [
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        true,
        false,
        false,
        false,
      ],
      [
        false,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        true,
        true,
        false,
      ],
      [
        false,
        false,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        false,
        false,
      ],
    ],
  },
  {
    id: 13,
    name: 'Ram',
    width: 15,
    height: 15,
    difficulty: 'medium',
    scheme: [
      [
        false,
        false,
        false,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        true,
        true,
        true,
        true,
        false,
        false,
      ],
      [
        false,
        false,
        true,
        false,
        true,
        true,
        true,
        true,
        false,
        true,
        false,
        false,
        true,
        true,
        false,
      ],
      [
        false,
        false,
        true,
        false,
        true,
        false,
        false,
        true,
        true,
        false,
        false,
        true,
        false,
        false,
        true,
      ],
      [
        false,
        false,
        true,
        true,
        false,
        true,
        false,
        true,
        false,
        true,
        false,
        false,
        false,
        false,
        true,
      ],
      [
        false,
        false,
        false,
        true,
        true,
        true,
        false,
        false,
        true,
        true,
        false,
        true,
        true,
        true,
        false,
      ],
      [
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        true,
        true,
        false,
        false,
        false,
        true,
        false,
        false,
      ],
      [
        true,
        false,
        true,
        true,
        true,
        true,
        true,
        false,
        true,
        false,
        false,
        false,
        true,
        true,
        false,
      ],
      [
        true,
        false,
        true,
        false,
        false,
        false,
        true,
        true,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
      ],
      [
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
      ],
      [
        false,
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        true,
        true,
        false,
      ],
      [
        false,
        false,
        true,
        false,
        true,
        true,
        true,
        false,
        true,
        false,
        false,
        true,
        true,
        true,
        false,
      ],
      [
        false,
        true,
        false,
        true,
        true,
        false,
        true,
        true,
        true,
        true,
        false,
        true,
        true,
        false,
        false,
      ],
      [
        false,
        true,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        true,
        true,
        false,
        true,
        false,
        false,
      ],
      [
        false,
        false,
        true,
        true,
        false,
        true,
        true,
        true,
        false,
        false,
        true,
        true,
        true,
        false,
        true,
      ],
    ],
  },
  {
    id: 14,
    name: 'Cow',
    width: 15,
    height: 15,
    difficulty: 'medium',
    scheme: [
      [
        false,
        false,
        false,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        true,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        true,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        true,
        true,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        false,
        false,
        false,
        false,
      ],
      [
        true,
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        true,
        true,
        true,
        true,
        true,
        false,
      ],
      [
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        true,
        true,
        true,
        true,
        true,
        true,
        false,
        false,
      ],
      [
        false,
        true,
        true,
        false,
        false,
        true,
        false,
        true,
        false,
        true,
        true,
        true,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        true,
        true,
        false,
        false,
        false,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
      ],
      [
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        true,
        true,
        true,
      ],
      [
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        true,
        true,
        true,
      ],
      [
        false,
        false,
        false,
        true,
        false,
        true,
        false,
        false,
        true,
        false,
        true,
        false,
        true,
        true,
        true,
      ],
      [
        false,
        false,
        false,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        true,
        false,
        false,
        true,
        true,
      ],
      [
        false,
        false,
        false,
        false,
        true,
        true,
        true,
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
    ],
  },
  {
    id: 15,
    name: 'Rose',
    width: 15,
    height: 15,
    difficulty: 'hard',
    scheme: [
      [
        false,
        false,
        false,
        false,
        true,
        true,
        true,
        false,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        true,
        false,
        false,
        true,
        true,
        false,
        true,
        true,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        true,
        false,
        true,
        true,
        false,
        false,
        true,
        false,
        true,
        true,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        true,
        true,
        false,
        false,
        true,
        false,
        false,
        false,
      ],
      [
        true,
        false,
        true,
        true,
        false,
        false,
        true,
        true,
        true,
        false,
        true,
        false,
        false,
        false,
        false,
      ],
      [
        true,
        true,
        false,
        true,
        true,
        true,
        true,
        true,
        false,
        false,
        true,
        true,
        false,
        false,
        false,
      ],
      [
        true,
        true,
        true,
        false,
        true,
        true,
        true,
        false,
        false,
        true,
        true,
        true,
        false,
        false,
        false,
      ],
      [
        false,
        true,
        true,
        true,
        false,
        false,
        false,
        true,
        false,
        true,
        true,
        false,
        false,
        false,
        true,
      ],
      [
        false,
        false,
        false,
        false,
        true,
        true,
        true,
        true,
        false,
        true,
        true,
        false,
        true,
        true,
        true,
      ],
      [
        false,
        false,
        true,
        true,
        true,
        true,
        true,
        false,
        true,
        true,
        false,
        true,
        true,
        true,
        true,
      ],
      [
        false,
        false,
        false,
        true,
        true,
        true,
        false,
        true,
        false,
        false,
        true,
        true,
        true,
        true,
        true,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        true,
        true,
        true,
        true,
        true,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        true,
        true,
        true,
        true,
        true,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        true,
        true,
        true,
        true,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
      ],
    ],
  },
];
